### ISSUE TITLE
connpass に https://web.womenwhogo.tokyo へのリンク・紹介を追加する

### ISSUE THREAD

**Issue by mi-bear** [WomenWhoGoTokyo/todo#2]
このページをちょっと充実させたいですね...などと思っています。
https://womenwhogo-tokyo.connpass.com

**Comment by mom0tomo** [comment]
![スクリーンショット 2020-07-06 12 15 53](https://user-images.githubusercontent.com/16359292/86552308-92eed200-bf82-11ea-834e-447994fa2c14.png)
勢い余ってリンクしているのが３カ所もありますが、こちらを追加・編集しました！（もとはwomenwhogotokyo.github.ioになっていたほうになっているものもweb.womenwhogo.tokyoの方にしました）

**Comment by mikkegt** [comment]
ももさん見ました。ご対応ありがとうございます。
https://web.womenwhogo.tokyo/ がリンクになってるといいんじゃないかな？と思いましたがいかがでしょうか？

**Comment by mom0tomo** [comment]
ご指摘ありがとうございます！修正しますです！

**Comment by mom0tomo** [comment]
![Screen Shot 2020-07-07 at 19 13 20](https://user-images.githubusercontent.com/16359292/86766818-09282d00-c086-11ea-8d40-10d0af05f4d5.png)
リンクにしてみました！！

**Comment by mikkegt** [comment]
確認しました。OKで良いかと思います。
ご対応ありがとうございました！

**Comment by mom0tomo** [comment]
ありがとうございます！！closeします！
