### ISSUE TITLE
Women Who Go Tokyo 7/28 (火) の募集ページを作る

### ISSUE THREAD

**Issue by mi-bear** [WomenWhoGoTokyo/todo#3]
前回の connpass 募集ページからコピーして作成すると良い！
次の STEP でやる内容が書いてあると、集まりやすかったりする...? と思っています。

次回は、STEP8-9 です。説明する内容は次のとおり。

- GROUP BY と集約関数 (sum, count)
- fmt.Printf の \t と %f
- HTTP ハンドラ
- HTTP サーバの起動
- html/template パッケージの使い方

SQL については奥が深いので、ちょっと厚めにお話したい気持ちあり。

**Comment by mikkegt** [comment]
イベントページの下書きを作成しました。

https://connpass.com/event/182118/edit/

- 開催日時を設定しました。（今回は19時30分〜）
- タイトルを設定しました。
- タイムテーブルを設定しました。
- STEP 08-09 で学ぶことを設定しました。

**Comment by mi-bear** [comment]
LGTM なやつです！ありがとうございます！

**Comment by mikkegt** [comment]
公開しました。

**Comment by mom0tomo** [comment]
LGTM!closeいたします
